name: Build for Windows 64-bit

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.*'
        modules: 'qtmultimedia'
        cache: true

    - name: Build tsMuxer
      run: |
        mkdir build
        cd build
        cmake ../ `
          -DTSMUXER_GUI=ON `
          -DCMAKE_BUILD_TYPE=Release `
          -DWITHOUT_PKGCONFIG=TRUE
        cmake --build . --config Release

        if (!(Test-Path "../bin")) { mkdir "../bin" }
        Copy-Item -Path "tsMuxer/Release/tsmuxer.exe" -Destination "../bin/tsMuxeR.exe" -Force
        if (Test-Path "tsMuxerGUI/Release/tsmuxergui.exe") {
          Copy-Item -Path "tsMuxerGUI/Release/tsmuxergui.exe" -Destination "../bin/tsMuxerGUI.exe" -Force
        }
        cd ..

    - name: Package Build
      run: |
        cd bin
        if (Test-Path "tsMuxerGUI.exe") {
          windeployqt --release --no-translations tsMuxerGUI.exe
        }
        if (Test-Path "w64.zip") { Remove-Item "w64.zip" }
        7z a -y w64.zip * '-xr!w64.zip'

    - uses: actions/upload-artifact@v4
      with:
        name: tsMuxer-w64
        path: bin/w64.zip
        if-no-files-found: error
      name: upload-artifact

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/w64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
